spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration/{vendor},classpath:db/seed/local # when you want to give test seed, add location test seed too

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

  kafka:
    producer:
      bootstrap-servers: 13.209.250.13:9092
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: 13.209.250.13:9092
      enable-auto-commit: false
    listener:
      ack-mode: manual

app:
  topic:
    labeled-data:
      pay-tmp-point-to-labeler: pay-tmp-point-to-labeler
      labeling-ocr-bounding-box: labeling-ocr-bounding-box

    verification: # 라벨링 검증 마이크로서비스의 Aggregate
      success-verity-labeling: success-verity-labeling # 라벨링 검증 성공 시, 네이밍 확인해봐야 함
      fail-verity-labeling: fail-verity-labeling # 라벨링 검증 실패 시, 네이밍 확인해봐야 함

    data: # data Aggregate
      success-labeler-labeled-data: success-labeler-labeled-data # 라벨러의 라벨링 성공
      record-verification-result: record-verification-result # 검증 결과를 LabeledResult에 기록