spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration/{vendor},classpath:db/seed/local # when you want to give test seed, add location test seed too

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: 13.209.250.13:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true

app:
  topic:
    preprocessing:
      ocr-data-preprocessing: ocr-data-preprocessing

    labeled-data:
      pay-tmp-point-to-labeler: pay-tmp-point-to-labeler
      labeling-ocr-bounding-box: labeling-ocr-bounding-box
      change-tmp-point-to-point: change-tmp-point-to-point # 임시포인트를 실제 포인트로 변환 이벤트
      delete-tmp-point: delete-tmp-point # 임시 포인트 삭제 이벤트

    verification: # 라벨링 검증 마이크로서비스의 Aggregate
      success-verify-labeling: success-verify-labeling # 라벨링 검증 성공 시, 네이밍 확인해봐야 함
      fail-verify-labeling: fail-verify-labeling # 라벨링 검증 실패 시, 네이밍 확인해봐야 함
      success-verify-text-label: success-verify-text-label # 텍스트 라벨 검증 성공 토픽

    data: # data Aggregate
      record-verification-result: record-verification-result # 검증 결과를 LabeledResult에 기록